### ISSUE TITLE
Query - Why is it not possible to create a rule between 2 objects from posted JSON ?

### ISSUE THREAD

**Issue by prade** [jruizgit/rules#111]
Hi,

Thanks for building a rules library that can integrate easily into any of the business systems. We are considering using durable_rules engine to solve some of the use cases that occur in our production system. 

In one of such cases, we would like to define a rule the following way : 

from durable.lang import *
with ruleset('test'):
    @when_all(m.paragraph.imatches(m.word))
    def say_hello(c):
        print ('Hello {0}'.format(c.m.paragraph))

    @when_start
    def start(host):
        host.post('test', { 'word': 'world', 'subject':'Hello world via rules' })

run_all()

I tried testing this and received an error : 2 - Unexpected type (uncommon) 

Is it possible to create such rule ? Or how do we go about solving it alternatively with what's already built ?

Thanks.

**Comment by jruizgit** [comment]
Hi, thanks a lot for reporting this issue. The `imatches` function only accepts strings because the regular expression is compiled at ruleset startup time. You can use facts and events as rvalues with other operators. Please see example in the link below:

https://github.com/jruizgit/rules/blob/master/docs/py/reference.md#facts-and-events-as-rvalues

**Comment by prade** [comment]
Thanks for your response, I have understood that we have to create a work around by creating facts on the rules initially based on the word and then work on the paragraph. 

I have tried the option of `('.*'+str(m.word)+'.*') ` too but the rule wasn't validated.
