### ISSUE TITLE
Error when running npm install durable

### ISSUE THREAD

**Issue by andyfensham** [jruizgit/rules#13]
Hi, getting the following when trying to install the javascript version for node.  Here is the error extract from the npm-debug.log

4606 error Windows_NT 6.3.9600
4607 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\andyf_000\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "durable"
4608 error node v5.9.0
4609 error npm  v2.6.0
4610 error code ELIFECYCLE
4611 error durable@0.36.2 install: `node-gyp rebuild`
4611 error Exit status 1
4612 error Failed at the durable@0.36.2 install script 'node-gyp rebuild'.
4612 error This is most likely a problem with the durable package,
4612 error not with npm itself.
4612 error Tell the author that this fails on your system:
4612 error     node-gyp rebuild
4612 error You can get their info via:
4612 error     npm owner ls durable
4612 error There is likely additional logging output above.
4613 verbose exit [ 1, true ]

**Comment by jruizgit** [comment]
Hi Andy, thank you for reporting the problem. I will be looking into this within the next couple of days.

**Comment by jruizgit** [comment]
Hi Andy, I have fixed the problems related to Windows. I also upgraded to the latest hiredis Windows version available. I have beed testing using Windows Server 2012 R2. Because Node.js native extension support for windows is not great, you will need to perform a few magic incantations:

1. Install VC++ build tools (http://go.microsoft.com/fwlink/?LinkId=691132), make sure you select Windows 8.1 and Windows 10 SDKs (if you don't select both, the installer will set the ucrt path incorrectly and node-gyp build will fail) 
2. Install Python 2.7 (https://www.python.org/downloads/) and add it to your PATH
3. npm config set python python2.7 (from cmd terminal)
4. npm config set msvs_version 2015 --global (from cmd terminal) 

At this point you can do:

- npm install durable
- Most likely you will be running your redis server outside your windows box, bind your ruleset to your server as follows

```javascript
var d = require('durable');

with (d.ruleset('a0')) {
    whenAll(m.amount.lt(100), function (c) {
        console.log('a0 approved from ' + c.s.sid);
    });
    whenStart(function (host) {
        host.post('a0', {id: 1, sid: 1, amount: 10});
    });
} 
d.runAll([{'host': 'jruiz.8zj18v.0001.usw2.cache.amazonaws.com', 'port': 6379, 'password': null}]);
```

I have been using an AWS EC2 instance, let me know if you need me to share the AMI.
