### ISSUE TITLE
Support for Lua as a rules language

### ISSUE THREAD

**Issue by freb** [jruizgit/rules#138]
I was wondering if you have any plans to support Lua for the definition of rules and implementation of the Alpha nodes. This is a different question/recommendation than was raised in #53.

The three supported languages are obviously much more popular than Lua, but Lua is the go-to choice for embedding. There are at least two data processing tools that use a Lua sandbox that could take advantage of Durable Rules (https://github.com/mozilla-services/heka and https://github.com/mozilla-services/hindsight).

Most languages have some support for embedding Lua so it might give those using other languages an option as well (#130).

I'm interested to hear your thoughts. Thanks for the awesome project.

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. I'm sorry for the delay in my reply. I have focused on supporting Python, Ruby and node.js because of the large audience. I haven't considered supporting Lua though. In fact I was thinking of implementing the Beta tree as a redis C extension and making redis optional. Offering the rules engine through Lua for embedded sandboxing sounds very interesting.

**Comment by freb** [comment]
I saw you talk a little about that during the Q&A in your redisconf 17 talk: <https://youtu.be/aRT8kfPmt-0?t=29m23s>. Which you should add to the README by the way.

Thanks again for your thoughts. I've really enjoyed watching this project progress.
