### ISSUE TITLE
multiple retractions

### ISSUE THREAD

**Issue by alonbg** [jruizgit/rules#227]
Hi @jruizgit 

What should be the expected consequent and match behaviour of the following:

- Only `single-signal`'s antecedent  gets matched.  Three times.
- Without the retraction  in `single-signal` gets matched twice and `three-signal` once.
- Does _async_  _action_ has any effect ?
- Deterministic ?
- I noticed _priority_ has no effect

```javascript
const d = require('durable');

d.ruleset('multiple_retract', function() {
   
    // three-signal
    whenAll: {
        signal1 = +m.date
        signal2 = m.date == signal1.date + 1
        signal3 = m.date == signal2.date + 1
    }
    runAsync: {
        retract(signal1);
        retract(signal2);
        retract(signal3);
        console.log('signals 1, 2 and 3');
        complete();
    }
   
   // single-signal
    whenAll: signal1 = +m.date;
    runAsync: {
        retract(signal1);
        console.log('signal1 ');
        complete();
    }

    whenStart: {
        host.assert('multiple_retract', { date: 20190525 });
        host.assert('multiple_retract', { date: 20190523 });
        host.assert('multiple_retract', { date: 20190524 });
    }
});

d.runAll();
```

BTW, today we have made our first [successful] end to end test with `durable-rules`.
Thank you for this great tool.

**Comment by jruizgit** [comment]
Hi, thanks for asking the question. Actually, the ruleset is working as expected:

1. The first assert is evaluated immediately and dispatched to the second rule
2. The second assert is evaluated immediately and dispatched to the second rule
3. The third assert is evaluated immediately and dispatched to the second rule

Because the second rule is always retracting, the first rule is never hit.
If you remove the assert in the second rule:

1. The first assert is evaluated immediately and dispatched to the second rule
2. The second assert is evaluated immediately and dispatched to the second rule
3. The third assert will match the first rule, which by default is prioritized first.

The third assert will not hit the second rule because it is retracted by the first rule.
