### ISSUE TITLE
Evaluate rules against object (Ruby)

### ISSUE THREAD

**Issue by jgluna** [jruizgit/rules#65]
Hi,

I'm working with custom objects in Ruby and I need to evaluate against some of the object properties in order to fire the rules, but the rules don't fire.

Let's say we have this Ruby class:

```
class TestClass
  def initialize(number_value = 0, boolean_value = false, string_value = '', array_value = [])
    @number_value = number_value
    @boolean_value = boolean_value
    @string_value = string_value
    @array_value = array_value
  end
  attr_accessor :number_value, :boolean_value, :string_value, :array_value
end
```

And we want to execute this flow:

```
Durable.flowchart :flow do
  stage :input
  to :init, when_all(m.subject.matches('.*'))

  stage :init do
    puts 'init'
    obj = Oj.load(m.subject.delete('\\'))
    obj.boolean_value = true
    s.subject = obj
  end
  to :second_step, when_all(s.subject.boolean_value == true)

  stage :second_step do
    puts 'second step'
  end

  when_start do
    post :flow, {:id => 1, :sid => 1, :subject => create_objects}
  end

end

def create_objects
  obj = TestClass.new(1,false,'object 1', ['array1','array2'])
  parsed_json = Oj.dump(obj)
  puts parsed_json
  parsed_json
end

Durable.run_all
```

If I debug this execution, the value of s.subject at the end of  **:init** is in fact the object with boolean_value = true, but **:second_step** is never executed. 

Is there a way to execute this flow or the value to be evaluated should be in the **s** variable like **s.boolean_value = true**?

Thanks.

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. Let me debug the scenario and I will report back.

Sent from my iPhone

On Feb 28, 2017, at 7:11 AM, Juan Luna <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I'm working with custom objects in Ruby and I need to evaluate against some of the object properties in order to fire the rules, but the rules don't fire.

Let's say we have this Ruby class:

class TestClass
  def initialize(number_value = 0, boolean_value = false, string_value = '', array_value = [])
    @number_value = number_value
    @boolean_value = boolean_value
    @string_value = string_value
    @array_value = array_value
  end
  attr_accessor :number_value, :boolean_value, :string_value, :array_value
end


And we want to execute this flow:

Durable.flowchart :flow do
  stage :input
  to :init, when_all(m.subject.matches('.*'))

  stage :init do
    puts 'init'
    obj = Oj.load(m.subject.delete('\\'))
    obj.boolean_value = true
    s.subject = obj
  end
  to :second_step, when_all(s.subject.boolean_value == true)

  stage :second_step do
    puts 'second step'
  end

  when_start do
    post :flow, {:id => 1, :sid => 1, :subject => create_objects}
  end

end

def create_objects
  obj = TestClass.new(1,false,'object 1', ['array1','array2'])
  parsed_json = Oj.dump(obj)
  puts parsed_json
  parsed_json
end

Durable.run_all


If I debug this execution, the value of s.subject at the end of :init is in fact the object with boolean_value = true, but :second_step is never executed.

Is there a way to execute this flow or the value to be evaluated should be in the s variable like s.boolean_value = true?

Thanks.

**Comment by jruizgit** [comment]
Hi, I took a quick look at the scenario. The object created by Oj.load cannot be serialized by the ruby json libray `JSON.generate()` used by durable_rules. The object generated looks like: `"{\"sid\":1,\"running\":true,\"subject\":\"#<TestClass:0x007f828d116b58>\"}"`

To illustrate the point. This flow works as expected:
```ruby
Durable.flowchart :flow do
  stage :input
  to :init, when_all(m.subject.matches('.*'))

  stage :init do
    puts 'init'
    s.subject = { 'boolean_value' => true }
  end
  to :second_step, when_all(s.subject.boolean_value == true)

  stage :second_step do
    puts 'second step'
  end

  when_start do
    post :flow, {:id => 1, :sid => 1, :subject => "test"}
  end

end
```
